// Generated by CoffeeScript 1.6.2
var fil, food, me, mul, _i, _len,
  __slice = [].slice;

mul = function() {
  var nums;

  nums = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  return nums.reduce(function(a, b) {
    return a * b;
  });
};

fil = function(container, liquid) {
  if (liquid == null) {
    liquid = 'coffee';
  }
  return "Filling " + container + " with " + liquid + "...";
};

me = {
  name: 'vinay',
  "class": 'web',
  age: 22
};

$.extend(defaults, options);

for (_i = 0, _len = foods.length; _i < _len; _i++) {
  food = foods[_i];
  if (food !== 'choclate') {
    food;
  }
}
